- .editorconfig
- CONTRIBUTING.md
- README.md
- docs/CODE_OF_CONDUCT.md
Now, finally, we will know how to contribute for once.
Closes #11
> Add contribution documentation

- README.md
Hotfixing the README, but via PR because I only live so dangerously.
> Clean up README typos and formatting

- .env.example
- .sequelizerc
- CONTRIBUTING.md
- README.md
- config/sequelize-config.js
- package.json
- yarn.lock
This PR sets up sequelize, pg, and dotenv as project dependencies, sets up the initial configuration, and creates the directory skeleton.
1. Set up a .env file that contains:
* DATABASE_URL_PRODUCTION :: The full database url to be used in production.
* DATABASE_URL_DEVELOPMENT :: The full database url to be used in development.
* DATABASE_URL_TEST :: The full database url to be used in testing.
2. Run `yarn install`
This resolves #17
> Add sequelize to project

- src/server/utils/logger.js
> Check for production env using utility method

- package.json
- src/scripts/scrapeCnnStatements.js
You can now call `yarn scraper:cnn -u /TRANSCRIPT/blahblahblah.html` and it will run the statement scraper on that page.
Results get output to INFO console.
Resolves #120
> Add a scraper test utility

- src/server/newsletters/templates/partials/boilerplateBottom.hbs
- src/server/newsletters/templates/partials/boilerplateTop.hbs
- src/server/newsletters/templates/partials/head.hbs
Simple text updates.
Resolves #91
Resolves #111
> Update newsletter boilerplate and ClaimBuster link

- src/server/queues/constants.js
- src/server/queues/nationalNewsletterDeliveryQueue/NationalNewsletterDeliveryJobScheduler.js
- src/server/queues/nationalNewsletterDeliveryQueue/NationalNewsletterDeliveryQueueFactory.js
- src/server/queues/nationalNewsletterDeliveryQueue/index.js
- src/server/queues/nationalNewsletterDeliveryQueue/nationalNewsletterDeliveryJobProcessor.js
This is it. This adds a national newsletter queue, scheduled every day at 9am (but in what timezone oooOOOoohhHHH?) (no but really, what timezone? will this be the deployed system's local time?)
Resolves #134
> Add national newsletter queue

- src/server/newsletters/constants.js
> Change national newsletter’s mailing list address

- src/server/newsletters/templates/partials/boilerplateBottom.hbs
> Add time range note to newsletter boilerplate

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
Whacking another honorific mole.
Resolves #244
> Filter out the honorific “FORMER”

- src/server/models/Claim.js
- src/server/queues/claimBusterClaimDetectorQueue/claimBusterClaimDetectorJobProcessor.js
In working on #268 we made some changes to the database, but missed updating the model.  This commit finished that by updating the model and the code that invokes the model.
Resolves #292
> Correct Claims model

- src/server/newsletters/NationalNewsletter.js
This modifies the way claims  are looked up for the national newsletter so that claims made by names matching known speakers are prioritized.  The logic is to attempt to fill the entire claim list with recent known-speaker-claims.  If there are not enough claims by known speakers, the query will then return claims made by other speakers.
There was a lot of discussion on the best way to implement this query. The truly best approach would be to leverage sequelize's "through" keyword in the query builder.  To do this, however, we would need an explicit association between claims and known_speakers.  That felt too heavy to implement today, since that association would imply a level of fidelity that the system simply does not provide.
For instance, we do no form of identity resolution; rather, …
> Add known speaker filter to national newsletter

- src/server/newsletters/NationalNewsletter.js
This PR adds logic to remove certain types of duplicate claims from appearing in the CNN portion of the national newsletter.
Specifically: 
1. Makes sure that our JOIN against known speakers does not accidentally create duplicate claims in the event that there are duplicate known speakers in the table.
2. Adds an additional clause to ensure that selected claims that have duplicates only result in the FIRST copy of the claim in the time window.
The query for the newsletter is starting to get a bit ridiculous, and may need to be refactored in the near future.
1. `yarn test`
2. `yarn newsletter:send-test --national`
None
Related to #109 -- We might want to mark it as resolved, though this doesn't cover all possible types of duplicate.
> Add CNN deduplication to national newsletter

- .travis.yml
- README.md
- package.json
This PR adds documentation and specification of the node version used by the project.
1. `yarn test`
- If you do not have Node 12 you may have to set up NVM / node 12
Resolves #340
> Specify Node 12.x

- src/server/newsletters/NationalNewsletter.js
This PR removes any claims from the national newsletter that are NOT known speaker claims.
1. `yarn test`
None
Resolves #371
> Remove backfill

- src/server/seeders/20200531171618-default-newsletters.js
This PR fixes the newsletter seed file
`yarn sequelize db:seed --seed 20200531171618-default-newsletters`
None
Resolves #376
> Fix seed file

- src/server/utils/__test__/twitter.test.js
- src/server/utils/twitter.js
This PR fixes the twitter account name extraction
1. `yarn test`
Resolves #381
> Improve twitter utility

- src/server/seeders/20200531171618-default-newsletters.js
- src/server/seeders/20201001091618-colorado-newsletter.js
This PR adds the colorado newsletter to the seed file
Resolves #383
> Add colorado newsletter

- src/server/seeders/20201010011612-wisconson-newsletter.js
This PR adds a seed file for the Wisconson alerts list.
Resolves #385
> Add Wisconson seed file

- src/server/seeders/20201010011612-wisconsin-newsletter.js
This PR fixes a typo / spelling screwup around the Wisconsin mailing list (lol TIL)
> Fix spelling

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
- src/server/workers/crawlers/CnnCrawlers/CnnTranscriptPortalCrawler.js
- src/server/workers/crawlers/CnnCrawlers/__test__/CnnTranscriptListCrawler.test.js
- src/server/workers/crawlers/CnnCrawlers/__test__/CnnTranscriptPortalCrawler.test.js
- src/server/workers/crawlers/CnnCrawlers/__test__/data/portalMock.html
- src/server/workers/crawlers/CnnCrawlers/__test__/data/transcriptListMock.html
This PR fixes the CNN crawler to recognize and properly parse CNN's new transcript URL standard.
Resolves #406
> Update CNN url formats
