- .babelrc
- package.json
- src/server/index.js
- src/server/workers/crawlers/AbstractCrawler.js
- src/server/workers/crawlers/HelloWorldCrawler.js
- yarn.lock
NOTE: it looks like this has the commits from #38; lets merge that and rebase before reviewing this.
This PR is the first step towards creating some common scraper tooling (#20)
Some notes about the design choices in this PR:
1. This sets up an AbstractCrawler and an example implemented crawler.
2. Crawlers pull out URLs to be scraped, scrapers pull out claims from URLs.
3. When we eventually build the scrapers we should consider having AbstractCrawler extend AbstractScraper. A lot of the general error handling, etc, will be common for both the crawlers and the scrapers.
4. This triggers the `HelloWorldCrawler` directly from `index.js`.  This will be replaced with something like an [EventEmitter](https://nodejs.org/api/events.html) eventually.
5. We may eventually want to have the crawler …
> Add scraper tooling

- config/sequelize-config.js
- src/server/migrations/20190516164909-create-claim.js
- src/server/migrations/20190516182547-create-speaker.js
- src/server/migrations/20190516183038-associate-claim-and-speaker.js
- src/server/models/claim.js
- src/server/models/index.js
- src/server/models/speaker.js
- src/server/seeders/20190516191610-demo-speakers-and-claims.js
Here we’ve got Sequelize models and migrations for claims and speakers, as well as a seed of each. After merging this, you’ll want to run `yarn migrate` and `sequelize db:seed:all` (the latter only if you actually want the seeds in your database, so, *not in production*).
By default, Sequelize camelCases tables and columns for consistency with the models and model attributes themselves, but we like to follow snake-case for SQL and camelCase for JavaScript. So there’s also some stitching here to make that mapping work properly. Just be aware that when referencing SQL field names (such as in migrations and seed files), you’ll want to use the snake-cased names (e.g. `created_at`), while using camelCase (`createdAt`) when referencing Sequelize/JavaScript model names/attributes. It can be …
> Add models and migrations for claims and speakers

- .babelrc
- .eslintrc
- .gitignore
- .travis.yml
- README.md
- package.json
- src/server/workers/crawlers/__test__/HelloWorldCrawler.test.js
- yarn.lock
For our testing, we’ve chosen [Jest](https://jestjs.io/). It’s fast, easy to setup, and easy to use. I’ve also created a simple example test for the `HelloWorldCrawler`.
Run tests with `yarn test`, or start a watcher with `yarn test:watcher`. Create tests for individual files as `{filename}.test.js`, and put them in a `__test__` directory alongside the file they test. E.g., `/src/server/Foo.js` is tested by `/src/server/__test__/Foo.test.js`.
Closes #39
> Add Jest testing framework and an example test

- src/server/config.js
- src/server/models/index.js
Instead of having to manually list any `.env`-set variables that we want added to our own `config` object (see substantially more description in #49), just grab all of `process.env`. Now we don’t have yet another place to add a new environment variable.
Closes #49
> Automatically config all process.env variables

- src/server/queues/AbstractJobScheduler.js
- src/server/queues/cnnTranscriptPortalCrawlerQueue/CnnTranscriptPortalCrawlerJobScheduler.js
- src/server/queues/cnnTranscriptPortalCrawlerQueue/CnnTranscriptPortalCrawlerQueueFactory.js
- src/server/queues/cnnTranscriptPortalCrawlerQueue/cnnTranscriptPortalCrawlerJobProcessor.js
- src/server/queues/cnnTranscriptPortalCrawlerQueue/index.js
- src/server/queues/constants.js
- src/server/queues/helloWorldCrawlerQueue/helloWorldCrawlerJobProcessor.js
- src/server/utils/__test__/crawler.test.js
- src/server/utils/crawler.js
- src/server/workers/crawlers/CnnCrawlers/CnnTranscriptPortalCrawler.js
- src/server/workers/crawlers/CnnCrawlers/__test__/CnnTranscriptPortalCrawler.test.js
- src/server/workers/crawlers/CnnCrawlers/index.js
- src/server/workers/crawlers/HelloWorldCrawler.js
CNN publishes transcripts on a continuous basis and has a few types of transcript list.  Specifically they have a transcript list for each day, show, and a special transcript list of "breaking news" transcripts.
All of these lists are linked to from a single transcript portal.
This commit creates the crawler of that portal.  It does not result in a list of transcript URLs but rather it returns a list of transcript list URLs which then need to be passed to a not-yet-written CnnTranscriptListCrawler.
This also kicks off a utils/crawler.js tool which abstracts common compound cheerio tasks that are not unique to specific crawlers.
One other non-breaking change I made to the AbstractCrawlScheduler is to make it possible for a descendant class to override the data passed to the scheduled jobs. …
> Add CNN transcript portal crawler

- package.json
- src/server/utils/logger.js
- yarn.lock
This adds winston as a dependency and sets up a logger for us to use throughout the project.  There is another PR that has to come next which replaces all instances of console.log with the logger.
Right now if you are not in production, all logs are written to disk in addition to being posted to terminal.  In production there are log files -- these need to be properly rotated to avoid disks being filled and killed.
We do not currently use any hosted log monitoring service, but winston makes it easy to set something like that up at some point in future.
Related to #34
> Add winston (logging)

- src/scripts/listScheduledJobs.js
- src/scripts/scheduleJobs.js
- src/scripts/unscheduleJobs.js
- src/server/index.js
- src/server/workers/crawlers/AbstractCrawler.js
This resolves #34 by actually using the logger to replace existing instances of console.log throughout the code base.  We may want to some day have a pass on existing queues to add more logging information.
> Remove consoles

- package.json
- src/scripts/runCrawler.js
- src/server/queues/cnnTranscriptListCrawlerQueue/CnnTranscriptListCrawlerJobScheduler.js
- src/server/queues/cnnTranscriptListCrawlerQueue/CnnTranscriptListCrawlerQueueFactory.js
- src/server/queues/cnnTranscriptListCrawlerQueue/cnnTranscriptListCrawlerJobProcessor.js
- src/server/queues/cnnTranscriptListCrawlerQueue/index.js
- src/server/queues/cnnTranscriptPortalCrawlerQueue/cnnTranscriptPortalCrawlerJobProcessor.js
- src/server/queues/constants.js
- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
- src/server/workers/crawlers/CnnCrawlers/CnnTranscriptListCrawler.js
- src/server/workers/crawlers/CnnCrawlers/CnnTranscriptPortalCrawler.js
- src/server/workers/crawlers/CnnCrawlers/index.js
This creates the crawler and parallel queue for the CNN transcript list pages.  These pages are basically just a list of links to actual transcripts.
This breaks out the helper functions for CNN transcripts and url parsing into its own utils/cnn.js
Related to issue #24
> Add CNN transcript list crawler

- .env.example
- README.md
- package.json
- src/scripts/sendTestEmail.js
- src/server/constants.js
- src/server/models/index.js
- src/server/utils/__test__/index.test.js
- src/server/utils/__test__/mailer.test.js
- src/server/utils/index.js
- src/server/utils/mailer.js
- src/server/workers/mailer/Mailer.js
- src/server/workers/mailer/__test__/Mailer.test.js
- src/server/workers/mailer/__test__/mailerTestData.js
- src/server/workers/mailer/index.js
- yarn.lock
This creates a generic `Mailer` class that interacts with the Mailgun API using the `mailgun-js` npm package. It also:
* Provides test coverage for `Mailer` and its utilities
* Provides a sample send-email script, called via `yarn mailer:send-test` with an email address provided via the `-r` parameter, e.g. `yarn mailer:send-test -r test@test.com`
Closes #22
> Add mailer and tests

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
- src/server/workers/scrapers/AbstractStatementScraper.js
- src/server/workers/scrapers/CnnTranscriptStatementScraper.js
Scrapers are slightly different from crawlers, though we may find reason to abstract common elements between the two since they both work with HTTP requests.
This implements our first scraper, the CNNTranscriptStatementScraper which takes a transcript URL and spits out statements (text attributed to a speaker).
These statements eventually need to be processed and passed to ClaimBuster, which will refine the statements into claims.
This does NOT create a queue for it.
Issue #24
> Implement CNN Transcript Scraper

- src/server/queues/cnnTranscriptListCrawlerQueue/cnnTranscriptListCrawlerJobProcessor.js
- src/server/queues/cnnTranscriptStatementScraperQueue/CnnTranscriptStatementScraperJobScheduler.js
- src/server/queues/cnnTranscriptStatementScraperQueue/CnnTranscriptStatementScraperQueueFactory.js
- src/server/queues/cnnTranscriptStatementScraperQueue/cnnTranscriptStatementScraperJobProcessor.js
- src/server/queues/cnnTranscriptStatementScraperQueue/index.js
- src/server/queues/constants.js
- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
- src/server/utils/logger.js
- src/server/workers/scrapers/CnnTranscriptStatementScraper.js
This creates a queue for the CNN transcript statement scraper.  It also includes a few little fixes to the scraper that came up in the first 30 seconds of testing.
Oh, it also has a little tweak to our logger so that errors render the stack trace; that should have always been there.
Related to Issue #24
> Add cnn transcript scraper queue

- package.json
- src/server/redis/client.js
- yarn.lock
This system already required redis in order to operate, since redis is what we use for queues.  This makes it possible to interact with redis in our application.
Related to issue #66 since we're going to be using redis to store crawl history
> Add redis to the project

- .env.example
- src/server/utils/logger.js
- src/server/workers/crawlers/AbstractCrawler.js
- src/server/workers/crawlers/__test__/HelloWorldCrawler.test.js
- src/server/workers/scrapers/AbstractScraper.js
- src/server/workers/scrapers/AbstractStatementScraper.js
- src/server/workers/scrapers/CnnTranscriptStatementScraper.js
Statement scrapes and crawls are both different types of scraper.  As described in #60, there is value in having both types of scraper extend a common class so we can avoid redundant supporting logic.
This PR implements that common class.  It also sneaks in a little bit of augmentation to our logger (and a bug fix where stack trace would render as undefined when a log line didn't include an error)
This resolves #60
> Create a common scrape class

- .travis.yml
- package.json
CI doesn’t benefit from coverage testing or verbose results, so configure Travis to use a special version without those options.
Closes #69
> Don’t do verbose coverage testing on CI

- src/server/constants.js
- src/server/migrations/20190703142652-add-affiliation.js
- src/server/models/speaker.js
- src/server/queues/AbstractJobScheduler.js
- src/server/queues/claimBusterClaimDetectorQueue/ClaimBusterClaimDetectorJobScheduler.js
- src/server/queues/claimBusterClaimDetectorQueue/ClaimBusterClaimDetectorQueueFactory.js
- src/server/queues/claimBusterClaimDetectorQueue/claimBusterClaimDetectorJobProcessor.js
- src/server/queues/claimBusterClaimDetectorQueue/index.js
- src/server/queues/cnnTranscriptStatementScraperQueue/cnnTranscriptStatementScraperJobProcessor.js
- src/server/queues/constants.js
- src/server/utils/__test__/claimBuster.test.js
- src/server/utils/__test__/cnn.test.js
- src/server/utils/claimBuster.js
- src/server/utils/cnn.js
- src/server/workers/claimDetectors/ClaimBusterClaimDetector.js
- src/server/workers/claimDetectors/index.js
This is the final major component of the full claim extraction pipeline.  This PR creates a worker and queue for interacting with ClaimBuster.  The queue is responsible for actually using the output (e.g. storing into a database), and the worker is just responsible for doing the interaction and returning the list of scored claims.
We may want to someday avoid codifying the name ClaimBuster in the models, but they're there at this point so I didn't want to tweak that in this PR.
There is more to be done around storing data correctly, but I'm going to create those needs as separate issues and declare that this PR resolves #21
> Integrate ClaimBuster

- src/scripts/sendTestEmail.js
Since we confirmed the domain with Mailgun in #61, we can send test emails to any recipient.
This is the tiniest PR ever and even asking for a review is an insult, so I'm going to Break With Protocol and merge it in.
> Remove note about verifying test email recipients

- package.json
- src/scripts/sendTestEmail.js
- src/server/newsletters/AbstractNewsletter.js
- src/server/newsletters/HelloWorldNewsletter.js
- src/server/newsletters/templates/default.hbs
- src/server/newsletters/templates/helloWorld.hbs
- src/server/newsletters/templates/helloWorldText.hbs
- src/server/newsletters/templates/partials/boilerplateBottom.hbs
- src/server/newsletters/templates/partials/boilerplateTop.hbs
- src/server/newsletters/templates/partials/foot.hbs
- src/server/newsletters/templates/partials/head.hbs
- src/server/utils/__test__/mailer.test.js
- src/server/utils/__test__/templates.test.js
- src/server/utils/mailer.js
- src/server/utils/templates.js
- src/server/workers/mailer/Mailer.js
- src/server/workers/mailer/__test__/Mailer.test.js
- src/server/workers/mailer/__test__/mailerTestData.js
- yarn.lock
* Import current designs (#28) and email boilerplate
* Automatically register Handlebars partials
* Apply design to Hello World newsletter
* Add Mailer support for HTML and text bodies
* Generate text versions of newsletters by stripping out the HTML
* Modify Hello World newsletter to include claim speakers
Note that the design and newsletter boilerplate will change in the future, and the claim/speaker association will change significantly once #88 is merged in.
Closes #29
> Add real designed HTML template

- src/server/constants.js
- src/server/migrations/20190809032905-rename-scraper-code.js
- src/server/models/claim.js
- src/server/newsletters/templates/national.hbs
- src/server/newsletters/templates/nationalText.hbs
- src/server/queues/claimBusterClaimDetectorQueue/claimBusterClaimDetectorJobProcessor.js
- src/server/utils/templates.js
- src/server/workers/claimDetectors/ClaimBusterClaimDetector.js
- src/server/workers/scrapers/CnnTranscriptStatementScraper.js
- src/server/workers/scrapers/constants.js
This inserts speaker name / affiliation into claims, and also exposes the URL and scraper name to statements (which can then be added to claims in a later commit)
Related to #99
> Expand on claim / statement metadata

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
This adds tests and support for speakers who have numbers in their affiliations.
Resolves #98
> Allow for numbers in speaker affiliations

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
Instead of listing all of the things an attribution can contain, lets just list out all of the things it can't.  The simple rule is that attributions never have lower case letters.
Attribution, name, and affiliation now use this logic instead.  If we find false positives cropping up then we can move from there.
Resolves #113 
Resolves #107
> Switch attribution regex to negatives

- src/server/workers/scrapers/AbstractScraper.js
This modifies `AbstractScraper.run()` to return a default/empty array when the scraping itself fails, and expands upon the debug message to note that it’s happening.
This allows downstream code to be able to always expect an array (though we will still want to wrap it in a try/catch block for safety).
Resolves #115
> Return a default value when scraper-running fails

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
Descriptors had a bug where only the first would be removed of certain types.  This fixes that, and also removes on camera descriptors.
Resolves #116
> Remove more descriptors

- src/server/workers/scrapers/CnnTranscriptStatementScraper.js
In the statement extraction pipeline we remove CNN affiliates.  We also normalize speakers so that last names and affiliations are applied to all speaker / statement pairs even if CNN truncates later in the transcript.  We were removing affiliated speakers BEFORE normalizing, meaning the normalization script did not have affiliations as part of the storage.
This changes the pipeline order so that normalization happens immediately after statements are extracted, and before any removal of "dud" statements.
Unfortunately we don't have integration tests set up for this pipeline, so there is no way to write a test as it goes beyond the functionality of individual utility methods.
Resolves #123
> Normalize speakers before removing affiliations

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
Line breaks were not being inserted in the correct location in places where (1) there were quotes and (2) there were multiple forms of punctuation ending a chunk (e.g. a `."` or `")`).
This corrects that RegEx to insert chunk breaks in the right place.
Resolves #131
> Correct line break insertion on speaker change

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
Parentheticals in affiliation names were not being removed, and furthermore hyphens in affiliations generally were causing chunks to be improperly split.  This corrects both of those problems.
Ultimately we need to DRY out the regular expressions as described in issue #64.  I have a feeling that edge cases aren't being fully corrected as we expand what an affiliation can look like.
Resolves #135
> Clean affiliation names more effectively

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
This removes `(through translator)` descriptors.  We really need a more generic RegEx to kick these out.
Resolves #141
> Remove "through translator" descriptors

- src/server/newsletters/NationalNewsletter.js
- src/server/newsletters/constants.js
The old value of 10 was a shot in the dark on my part. Changing to 15 to match current newsletter.
BTW I'm pretty sure this will soon be a constant, but I'm only planning to do that if 15 is our common limit (i.e. once we add other claim types / newsletters), not just to get limit literals out of the class definition.
Resolves #133
> Increase newsletter claim limit to 15

- .env.example
- src/server/newsletters/AbstractNewsletter.js
- src/server/newsletters/constants.js
- src/server/utils/__test__/newsletters.test.js
- src/server/utils/newsletters.js
We gain a new .env example (`MAILING_LIST_OVERRIDE `) that, when configured, replaces the newsletter-specific mailing list configuration. This mostly exists to let us setup otherwise-production environments that are globally configured to send only to internal mailing lists until otherwise let off the leash to send to their true configured mailing lists.
NB: This still has the old guards that won’t let us accidentally configure local development environments to send to the real lists. (Or, it shouldn’t. I’m scared to test.) If you ever want to do that, you will have to manually get in there and remove the guards and may God have mercy on your soul.
This also moves the function that composes mailing list email addresses off of `AbstractNewsletter` and to a utility function where it …
> Allow envs to set a global mailing list override

- src/server/queues/claimBusterClaimDetectorQueue/ClaimBusterClaimDetectorJobScheduler.js
- src/server/queues/cnnTranscriptListCrawlerQueue/CnnTranscriptListCrawlerJobScheduler.js
- src/server/queues/cnnTranscriptStatementScraperQueue/CnnTranscriptStatementScraperJobScheduler.js
The actual `Schedules` property for “no schedule” is `NONE`, but we were referencing it as `None`, causing an `undefined` to be passed to the cron-parser that Bull uses. Besides being wrong, this was throwing an error (that we aren’t catching, whoops) that tripped up scheduling.
Even after making this change, I’m still seeing two other `undefined`s passed to cron-parser, so there’s still more work to be done here.
Affects #150
> Fix reference to null schedule

- src/server/queues/AbstractJobScheduler.js
- src/server/queues/constants.js
Our scheduler uses cron-style schedule strings. By default, these follow the system clock on whatever machine is executing the queue. This is a problem when you want something to happen at some universal time no matter what machine it’s run on. The obvious answer is “just express it in UTC”, but _that’s_ a problem if we’re very US-centric and want the schedule to remain fixed at a clock time regardless of daylight savings changes, such that “8am Eastern” means 8am in summer and winter.
Turns out our scheduler, Bull, supports specifying which timezone your configuration is in, and then translates that to the host system clock appropriately.
We’re setting our schedule to be relative to New York City, since it’s the greatest city in the world, greatest city in the world (work, work).
While …
> Add timezone support to scheduler

- src/server/queues/helloWorldCrawlerQueue/HelloWorldCrawlerJobScheduler.js
The `HelloWorldCrawler` was still scheduled to run every minute, even though it was just a proof of concept. Disabling that so we aren’t unnecessarily crawling google.com and extracting URLs.
Resolves #159
> Disable HelloWorldCrawler schedule

- src/server/queues/cnnTranscriptPortalCrawlerQueue/CnnTranscriptPortalCrawlerJobScheduler.js
Running the crawler every minute is a bit eager.
Resolves #171
> Slow down CNN transcript crawler to hourly

- src/scripts/listScheduledJobs.js
- src/scripts/scheduleJobs.js
- src/scripts/unscheduleJobs.js
The job-scheduling tasks run a series of promises. Before this change, we weren’t catching rejected promises, so a problem with any of them (1) wasn’t handled gracefully and (2) never exited the process, since `process.exit()` was called during the first `then()`, which assumes resolution.
Fixed (1) by adding a `catch()` with error-logging and (2) by moving the `process.exit()` to a `finally()` that executes in all cases.
(Note: `Promise#finally()` is still a draft and not supported by IE in-browser, but is supported in Node v10+.)
Resolves #150
> Handle rejected promises in job-scheduling tasks

- package.json
- src/scripts/runCnnCrawler.js
- src/scripts/runCrawler.js
- src/server/index.js
- src/server/queues/AbstractJobScheduler.js
- src/server/queues/AbstractQueueFactory.js
- src/server/queues/claimBusterClaimDetectorQueue/ClaimBusterClaimDetectorJobScheduler.js
- src/server/queues/cnnTranscriptListCrawlerQueue/CnnTranscriptListCrawlerJobScheduler.js
- src/server/queues/cnnTranscriptListCrawlerQueue/cnnTranscriptListCrawlerJobProcessor.js
- src/server/queues/cnnTranscriptPortalCrawlerQueue/CnnTranscriptPortalCrawlerJobScheduler.js
- src/server/queues/cnnTranscriptPortalCrawlerQueue/cnnTranscriptPortalCrawlerJobProcessor.js
- src/server/queues/cnnTranscriptStatementScraperQueue/CnnTranscriptStatementScraperJobScheduler.js
- src/server/queues/cnnTranscriptStatementScraperQueue/cnnTranscriptStatementScraperJobProcessor.js
- src/server/queues/helloWorldCrawlerQueue/HelloWorldCrawlerJobScheduler.js
- src/server/queues/nationalNewsletterDeliveryQueue/NationalNewsletterDeliveryJobScheduler.js
- src/server/utils/queue.js
I spent a lot of time digging around and documented that outcome in [this potentially relevant bull issue](https://github.com/OptimalBits/bull/issues/923#issuecomment-522665737).
We had misunderstood Bull's concurrency mechanism, and whenever we generated a new queue we would create a queue with the processor attached.  This actually meant that every single time we ran getQueue() we were also creating a new job processor for that queue.
This meant that instead of having one job processor per queue we were having... many more.
This commit creates two types of Queue factory method:
1. getInsertionQueue -- this creates a queue objec t solely for the purpose of inserting new jobs.  Generally speaking this is the method that will be called.
2. getProcessingQueue -- this creates a queue object …
> Split getQueue into two methods

- src/server/newsletters/templates/partials/head.hbs
This is discussed more in the attached issue, but essentially not all email clients pay attention to media queries. This was a problem because our mobile styles are more important than our desktop styles, and in the event that one of those scenarios will be ignored, we want the desktop styles ignored.
So this inverts our behavior so that the mobile styles are the defaults, and we apply desktop styles with media queries, rather than the reverse.
Resolves #165
> Invert media queries to default mobile

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
Straightforward: we strip `REPRESENTATIVE`, `SENATOR`, and `SEN.` but missed `REP.`.
Resolves #178
> Remove `REP.` prefix from speaker name

- src/scripts/scheduleJobs.js
- src/server/queues/AbstractJobScheduler.js
We have the ability to create a job scheduler that should not actually be scheduled by configuring its schedule as `NONE`. Problem is, we still added a repeatable job to the queue, but with an invalid cron pattern. What we should’ve been doing is not schedule these jobs at all; `NONE` should make them a scheduling no-op.
This commit makes that real (jazz hands). Now the `scheduleJobs()` verifies the schedule isn’t `NONE` before scheduling it, else it returns `null`. (This does mean any code that checks the return value of `scheduleJobs()` should know that it may receive a `Job` object _or_ a `null` value. Thus the [`filter(job => !!job)` guardrail on the `scheduleJobs.js` task](https://github.com/TechAndCheck/tech-and-check-alerts/blob/b19aad2ff2b2cf70d00338a8282591d6e6e232a8/src/scripts/s …
> Stop scheduling jobs that have a `NONE` schedule

- src/server/utils/__test__/index.test.js
- src/server/utils/__test__/scraper.test.js
- src/server/utils/index.js
- src/server/utils/scraper.js
- src/server/workers/scrapers/CnnTranscriptStatementScraper.js
Because of line breaks and formatting, we often end up with claims full of multiple spaces between words. This gets visually collapsed to a single space in most rendering situations (like HTML), but we shouldn’t rely on that, and we should clean these down to single spaces when possible.
This adds a generic `squish()` utility (named after Ruby’s), plus a scraper utility for iterating over statements and squishing their text, plus tests, and then adds that squish utility to the `CnnTranscriptStatementScraper` sequence of statement-cleaning functions.
Resolves #106
> Collapse repeated whitespace to a single space

- src/server/utils/__test__/cnn.test.js
- src/server/utils/cnn.js
For some reason, `http://cnn.com/TRANSCRIPTS` URLs perform some server magic that Chrome tolerates but which ties up Firefox and Safari, while the `http://transcripts.cnn.com/TRANSCRIPTS` variant works universally.
Modify our tests and utilities to always prefer the safer one so that Firefox and Safari users can actually use the transcript links in the newsletters.
Resolves #143
> Canonize CNN URLs as transcripts.cnn.com

- src/server/newsletters/NationalNewsletter.js
Subscribers like to be able to quickly see the platforms scraped and the day’s date in the subject line of the newsletters.
Resolves #184
> Add platforms and date to newsletter subject line

- src/server/migrations/20190828142735-create-twitter-accounts.js
- src/server/models/TwitterAccount.js
Our twitter scraper is not going to be scraping everything on twitter, so we need a mechanism to specify which accounts are of interest.
This commit creates the migration and model for tracking which accounts are which.  The list_name column allows us to have more than one "bucket" that the accounts are in (which will be needed for the short term as we have localized newsletters)
This table will be populated in a separate scrape of the existing google spreadsheets for the two twitter lists; eventually we may want to explore a local administrative interface for that list management.
Related to #26
> Add twitter accounts table

- src/server/workers/mailer/constants.js
While not entirely necessary, for best deliverability Mailgun suggests both (1) fully validating the domain by pointing MX records to Mailgun (which means you can’t receive email elsewhere for that domain) and (2) using the validated domain as the domain for the “from” email address.
In order to achieve №1 (a fully-validated domain with MX records) without messing up existing mail delivery to `factstream.co`, we used `alerts.factstream.co`. But then we violated №2 by using `alerts@factstream.co` as the from address, because it's nicer.
However, besides reducing deliverability, this also made some email clients complain (see #166).
So! We decided to pick a more convoluted but also more reliable "from" email address rooted at `alerts.factstream.co` to fix all that.
Resolves #166
Resolves …
> Change from address to alerts.factstream.co domain

- yarn.lock
Ran `yarn upgrade` to get latest available/matching versions of all our dependencies.
The primary goal was making sure lodash was updated to resolve the security vulnerability, but I went ahead and let everything update (and tested to ensure no regressions).
Resolves #81
> Update npm dependencies to latest versions

- src/server/constants.js
- src/server/newsletters/NationalNewsletter.js
- src/server/newsletters/constants.js
- src/server/newsletters/templates/national.hbs
- src/server/newsletters/templates/nationalText.hbs
- src/server/newsletters/templates/partials/head.hbs
- src/server/utils/templates.js
- src/server/workers/scrapers/constants.js
Following on the addition of the `TWITTER_ACCOUNT` scraper, this adds scraped tweets to the National newsletter. There was an unexpected amount of related tinkering to make this work well.
* Change the expected structure of the body data so that a single `claims` object is returned, keyed by medium (currently `TV` and `SOCIAL`).
* Move the generation of the date scope out of the query paramater itself and to an instance attribute set at creation time, so that repeated queries for this instance will share the same scope.
* Add social claims to the newsletter templates.
* Since it's now possible — though weird — for one medium to have claims while the other doesn't, this adds fallback language to each medium's section in the template. (If both media have no claims, the preflight assertion …
> Add Twitter claims to National newsletter

- package.json
- src/scripts/runTwitterScraper.js
- src/server/queues/constants.js
- src/server/queues/twitterScrapeInitiationQueue/TwitterScrapeInitiationJobScheduler.js
- src/server/queues/twitterScrapeInitiationQueue/TwitterScrapeInitiationQueueFactory.js
- src/server/queues/twitterScrapeInitiationQueue/index.js
- src/server/queues/twitterScrapeInitiationQueue/twitterScrapeInitiationJobProcessor.js
- src/server/utils/__test__/claimBuster.test.js
- src/server/utils/claimBuster.js
- src/server/workers/claimDetectors/ClaimBusterClaimDetector.js
*NOTE: Review #203 first, then we need to merge and potentially rebase before reviewing this (this contains all of the changes of 203)*
With this PR the twitter scraper will actually work (note that it won't scrape anything unless the twitter_accounts table has data in it).
This also adds a utility script similar to the cnn pipeline utility script, which allows you to manually run the twitter scrape pipeline for testing purposes.
Since this actually invokes the twitter pipeline we also learned about a few kinks in claimbuster; specifically that claimbuster can't handle statements with forward slashes (e.g. tweets containing urls).
Issue #26 
Resolves #204
> Add twitter kickoff queue

- src/server/newsletters/NationalNewsletter.js
Before, the time window we used for fetching claims for the newsletter was problematic in two ways:
1. The starting point for calculating the 24-hour time window was the moment the class was created; thus, tiny variations in starting time each day could result in sequential days either overlapping their time windows or leaving a gap between them.
2. We used an unbounded `>=` query, which introduced another possibility of duplicate claims on sequential days.
This resolves (1) by backing the query up to the start of the hour to round off any drift in start time and (2) setting a hard `<` bound on the upper end of the query.
As a bonus, we can remove the slightly gross use of `this.createdAtHorizon`, since the time drift between medium queries that it resolved is now avoided.
Resolves #206
> Fetch claims with more stable time window

- src/server/utils/__test__/twitter.test.js
- src/server/utils/twitter.js
For backwards-compatibility with clients expecting Twitter’s original 140-character limit, the Twitter API truncates tweets by default. You have to explicitly request the longer versions, and change which field you read the tweet content from.
This adds the necessary parameter and modifies which field we draw the tweet content from.
It also changes how we compose the query string parameters from a long direct string manipulation to an object-to-query-string conversion using Node's built-in `querystring`.
Resolves #213
> Fetch full tweets using Twitter API extended mode

- docs/TESTING.md
- package.json
- src/scripts/generateCnnUtilTest.js
- src/server/utils/__test__/cnn.test.js
- src/server/utils/__test__/data/cnn/index.js
- src/server/utils/cnn.js
- src/server/workers/scrapers/CnnTranscriptStatementScraper.js
- src/server/workers/scrapers/GenericScraper.js
- src/server/workers/scrapers/constants.js
This PR creates a mechanism (and utility) for us to easily expand the CNN test suite to include real world data as we find instances of the system failing.
For documentation on how to use these tools meaningfully go check the new `docs/TESTING.md` which is part of this PR.
run `yarn generate:test:cnn -u [FULL_TRANSCRIPT_URL_HERE]`
Resolves #127 
Related to #47 since we technically now have TESTING.md
> Automated automated testing for CNN pipeline

- src/server/workers/scrapers/CnnTranscriptStatementScraper.js
We accidentally approved some buggy code recently.  This fixes the CNN scraper again.
To test the CNN scraper type:
```
yarn scrape:cnn -u /TRANSCRIPTS/1908/22/cnnt.01.html
```
This is a hotfix; no issue.  If @reefdog can't review I'll just merge since this is a breaking bug.
> Fix util import

- src/server/migrations/20190912192137-change-scrape-url-type.js
- src/server/models/ScrapeLog.js
Previously, we defined the `ScrapeLog.scrapeUrl` attribute (in Postgres terms, `scrape_logs.scrape_url`) using the Sequelize `STRING` shorthand with no length, which meant it defaulted to 255. As with `StatementLog.canonicalUrl`, a more appropriate length for URLs is 1024.
This adjusts the model definition and adds a Sequelize migration to change the database column. Consequently, you should run migrations after merging this commit.
Resolves #242
> Increase length of scrape_logs.scrape_url field

- src/server/queues/constants.js
- src/server/queues/northCarolinaNewsletterDeliveryQueue/NorthCarolinaNewsletterDeliveryQueueFactory.js
The North Carolina newsletter components were created from copying the National one, but we left behind a reference to the National queue.
This fixes that by correctly describing and using a North Carolina queue.
Hopefully someone will actually review this one.
Resolves #246
> Repair North Carolina queue factory

- src/server/newsletters/NationalNewsletter.js
- src/server/newsletters/NorthCarolinaNewsletter.js
- src/server/queues/claimBusterClaimDetectorQueue/claimBusterClaimDetectorJobProcessor.js
- src/server/utils/twitter.js
- src/server/workers/claimDetectors/ClaimBusterClaimDetector.js
- src/server/workers/scrapers/AbstractStatementScraper.js
We’ve had a `Claim.claimedAt` attribute, but haven’t been using it. Instead, we've been using `createdAt` as a proxy.
This PR adds the infrastructure for scrapers to populate `Claim.claimedAt`; modifies newsletters to query by `claimedAt` rather than `createdAt`; and updates the Twitter scraper to populate the field. It will take longer to reliably scrape `claimedAt` for CNN (see #100), so those will continue to fall back to the scrape time instead.
After deploying, we should run `UPDATE claims SET claimed_at = created_at WHERE claimed_at IS NULL` for backwards-compatibility.
Affects #100
Resolves #258
> Support `Claim.claimedAt` and use it for Twitter

- src/server/migrations/20190915180014-increase-claim-column-length.js
- src/server/models/Claim.js
This commit adds a migration to change the length of three `claims` table columns and modifies one `Claim` model attribute definitions to match the existing column (which was, incidentally, more correct).
Previously, we had a mismatch between our Sequelize model definition for Claims and the actual table structure. (That this is possible belies a bit of a problem in Sequelize itself, but I digress.) Four of the fields were defined as 1024 characters long in the model, but used the default 255-character length in their original migrations.
One of those fields, `scraper_name`, didn’t actually need to be 1024 anyway, so this changes the model definition. The other three could arguably fit into less than 1024 in many cases (especially `source`), but there’s no harm in making them long enough …
> Match up Claims table and model definitions

- src/server/queues/AbstractQueueFactory.js
When the scrapers were running we were slowly accumulating jobs in redis which over time essentially served as a memory leak.  This updates our queues to default to deleting jobs upon completion.
Resolves #261
> Remove jobs on completion by default

- src/server/migrations/20191001161648-add-is-active-to-twitter-accounts.js
- src/server/models/TwitterAccount.js
- src/server/queues/twitterScrapeInitiationQueue/twitterScrapeInitiationJobProcessor.js
- src/server/utils/newsletters.js
We periodically update the Twitter accounts we want to scrape. Rather than deleting them from the database, we want to be able to deactivate and reactivate them, and we want the scrape and newsletter composition queries to scope by active state.
This PR adds the fundamental concept of `TwitterAccount.isActive`, including its database migration (and column configuration) and scoping relevant queries.
This lays the foundation for #255 but does not resolve it because it doesn't provide any functions or examples for changing the active state.
Note: you must run migrations after merging this PR.
> Add active/inactive concept to TwitterAccount

- docs/TESTING.md
This attempts to capture the practices we have invoked so far.
There are still some areas that are not fleshed out (e.g. integration testing instructions) but there is no need to invent that until we actually begin to write integration tests.
Resolves #47
> Add more robust TESTING.md documentation

- src/server/models/TwitterAccount.js
- src/server/utils/__test__/index.test.js
- src/server/utils/__test__/twitter.test.js
- src/server/utils/__test__/twitterTestData.js
- src/server/utils/index.js
- src/server/utils/twitter.js
- src/server/workers/scrapers/TwitterAccountStatementScraper.js
By design, we intended to associated Twitter claims with the human-curated “preferred display name” stored in `TwitterAccount.preferredDisplayName`. Previously, though, we were just using the Twitter account’s scraped name.
Now, we actually use the preferred display name from the database, if it exists and is non-empty.
Resolves #249
Note: because we introduced new references to `speaker.name`, either this branch or #268 will need adjusting based on who gets merged first.
> Save Twitter claims using preferred display name

- src/server/utils/__test__/twitter.test.js
- src/server/utils/__test__/twitterTestData.js
In #257, we added a file for Twitter test data, but only used it for data relevant to that PR. This PR completes the transition by moving remaining test data out of the test file itself.
Resolves #270
> Move Twitter test data to Twitter test data file

- package.json
- src/server/utils/__test__/google.test.js
- src/server/utils/google.js
- src/server/workers/scrapers/GoogleSpreadsheetScraper.js
- src/server/workers/scrapers/constants.js
- yarn.lock
This creates the ability to scrape a google spreadsheet, this worker will be used in the queues created for #229 and #280 since google spreadsheets are the initial mechanism for updating things like twitter and priority speaker lists.
This creates a new dependency on a utility package called [csv-parse](https://www.npmjs.com/package/csv-parse) (which I think is necessary because please do not make me write my own CSV parser.)
> Add google spreadsheet scraper

- package.json
- yarn.lock
This patch primarily is being made to get rid of the security
vulnerability notification on github.  The vulnerability didn't actually
affect our code base since the relevant method in the sub-library was
not being invoked by parcel.  Nevertheless, security warnings look scary
and are worth addressing even if they are inaccurate!
This also updates the lockfile to use the latest babels that fit our package versions on the next install (though we may want to consider locking those into specific versions to prevent these sorts of indirect updates whenever yarn install is run)
Resolves #285
> Update parcel to 1.12.4

- src/server/constants.js
Previously, Claimbuster only offered the dev version of the API.
They recently added a production version and requested we switch to it.
Resolves #290
> Update Claimbuster API endpoint

- src/server/utils/__test__/twitterTestData.js
- src/server/utils/twitter.js
In #268 and #294, we updated the Claim model to split `speakerName` into two fields, (`speakerExtractedName` and `speakerNormalizedName`). Our speaker name normalizers are supposed to store the original extracted name in both fields, then normalize the name and store it in `speakerNormalizedName`.
We made this change for CNN, but not for Twitter. This change covers Twitter.
Resolves #298
> Fix Twitter scraper to normalize speaker name

- src/server/newsletters/templates/national.hbs
- src/server/newsletters/templates/nationalText.hbs
- src/server/newsletters/templates/northCarolina.hbs
- src/server/newsletters/templates/northCarolinaText.hbs
In #268 and #294, we updated the Claim model to split `speakerName` into two fields, (`speakerExtractedName` and `speakerNormalizedName`, with the latter intended for display) but didn’t flow this change down to the newsletter.
This change correctly displays the normalized name in the newsletter.
Resolves #297
> Repair newsletter display of claim speaker

- package.json
- src/server/workers/claimDetectors/__test__/ClaimBusterClaimDetector.test.js
- yarn.lock
This is the first part of a push for adding tests to components.  It is not quite an integration test, but invokes more high level code than a simple unit test might.
To test the ClaimBusterClaimDetector we needed to mock ClaimBuster API responses.  We're using [`nock`](https://www.npmjs.com/package/nock) for this.
This is not changing functionality, so testing simply involves invoking the tests:
`yarn test`
You'll have to `yarn install` before you can run tests.  Arguably you could just look at the CI outcome to know if the tests pass...
> Add tests for ClaimBusterClaimDetector

- src/server/utils/__test__/cnn.test.js
- src/server/utils/__test__/crawler.test.js
- src/server/utils/__test__/scraper.test.js
- src/server/workers/crawlers/HelloWorldCrawler.js
- src/server/workers/mailer/__test__/mailerTestData.js
This replaces test urls like google.com and pants.com with variations of example.com, example.net, etc. 
Resolves #207
> Set test urls to placeholder domains

- src/server/workers/crawlers/CnnCrawlers/__test__/CnnTranscriptListCrawler.test.js
- src/server/workers/crawlers/CnnCrawlers/__test__/CnnTranscriptPortalCrawler.test.js
- src/server/workers/crawlers/CnnCrawlers/__test__/data/portalMock.html
- src/server/workers/crawlers/CnnCrawlers/__test__/data/transcriptListMock.html
This add two new component tests, one for CnnTranscriptListCrawler and one for CnnTranscriptPortalCrawler.
The tests raise the concern that, at least in the case of the portal crawler, the currently-in-spec functionality is not ideal (see #278) but these tests currently match the implementation.
RElated to #309
> Add CNN crawler tests

- .travis.yml
TravisCI does not allow the use of environment variables when setting known hosts.  This has two effects for us:
1. It means that the ssh_known_hosts apparently never did anything
2. It means TravisCI has some error output when trying to set up known
hosts using environment vars.
This removes the offending attempt.  I don't expect there to be any consequence for our CD processes.
Resolves #322
> Remove ssh_known_hosts TravisCI addon

- .travis.yml
- README.md
- config/sequelize-config.js
- package.json
- src/test/suiteSetup.js
This adds in the pipework to allow our tests to interact with a database.
It migrates the test database when tests are run, adds Travis support for postgres, adds some protection to make sure tests are never run on a production / dev database, and also fixes an issue with database connections that became a blocker after enabling the test DB on CI.
This does not look like a week of work but there was a big struggle / rabbit hole as outlined in [this SO issue](https://stackoverflow.com/questions/60217417/jest-tests-hang-due-to-open-sequelize-connections)
Just run tests. (`yarn test`)
You will probably find that you need to update your environment variables so that your test DB is different from your prod / dev DB.  Since we weren't using test DB in the past it's likely that they were all …
> Add support for a test database

- src/server/queues/cnnTranscriptListCrawlerQueue/cnnTranscriptListCrawlerJobProcessor.js
Previously, before scraping a CNN transcript URL, we performed a preflight check in this order:
1. Check the database: Have we ever scraped this URL before?
2. Extract the transcript date from the URL: Is it beyond our configured date horizon?
With that order, we _always_ hit the database, even when we’re going to reject the scrape in the very next check.
Since the order is not technically meaningful, we can reverse it to save ourselves many unnecessary database lookups.
This commit does just that.
Run the CNN portal crawler with `yarn queue:jobs:run:cnn-portal-crawler` and make sure nothing blows up. (If you wanted to, you could fiddle with your date horizon and do some performance profiling, but that seems extreme.)
None. Fire and forget.
Resolves #277
> Don’t check scrape time if beyond scrape horizon

- .travis.yml
We did not have deployment in its own build stage, which means deployment was happening for every set of tests.
This PR adds support for build stages in Travis to ensure that deployment only occurs once, and only after all tests pass.
Unfortunately this can only be tested by opening a PR since it has to do with our CI service.
No deployment necessary
Resolves #336
> Add build stages to travis

- src/server/migrations/20200225232115-refactor-scrape-logs-response-status.js
- src/server/models/ScrapeLog.js
- src/server/workers/scrapers/AbstractScraper.js
- src/server/workers/scrapers/constants.js
Previously, we stored each scrape's complete `result` or `error` response data in the `scrape_log` table for every scrape logged. This was fine during development, but is much weightier than necessary for permanence. For instance, we've accumulated 4.6GB of `result` data in production in fewer than five months. (We've stored 5MB of `error` data in the same time.)
This change replaces the `scrape_log.result` and `scrape_log.error` text columns with two new columns:
- `scrape_log.scrape_response_code` for storing the HTTP response code, or a `non-http-error` fallback
- `scrape_log.scrape_response_message` for storing an optional longer message, currently only used for storing error messages
It also adapts the `ScrapeLog` model to use these columns and includes a complex migration that …
> Store scrape log data more efficiently

- src/server/queues/cnnTranscriptListCrawlerQueue/cnnTranscriptListCrawlerJobProcessor.js
Before this change, we wouldn’t re-scrape a CNN URL that we’d already seen before, even if the scrape was unsuccessful. This protects us from repeatedly scraping broken links in perpetuity, but also means if a URL was temporarily broken, we don’t retry it later.
With the `SCRAPE_DAY_HORIZON` guard protecting us from scraping permanently-broken URLs in perpetuity, we’re going to go ahead and retry scraping broken URLs.
1. `yarn test` to make sure nothing breaks.
2. `yarn queue:jobs:run:cnn-portal-crawler` to make sure scraping still works.
None.
Resolves #337
> Retry unsuccessful CNN scrapes

- package.json
- yarn.lock
This PR removes some of the bloat from our start script.  Specifically we never actually used parcel.  Removing parcel allows us to remove several start scripts, as well as the `concurrently` package.
1. `yarn test`
1. `yarn start`
- `yarn install`
I don't think this will remove the old dependencies; if you want a truly clean dependency set you should probably run `rm -fr node_modules` before `yarn install`
Resolves #334 
Related to #335
> Clean start scripts

- package.json
- src/scripts/runTwitterAccountListScraper.js
- src/server/constants.js
- src/server/migrations/20200406190114-add-twitter-account-unique-key.js
- src/server/models/TwitterAccount.js
- src/server/queues/constants.js
- src/server/queues/twitterAccountListScrapeInitiationQueue/TwitterAccountListScrapeInitiationJobScheduler.js
- src/server/queues/twitterAccountListScrapeInitiationQueue/TwitterAccountListScrapeInitiationQueueFactory.js
- src/server/queues/twitterAccountListScrapeInitiationQueue/index.js
- src/server/queues/twitterAccountListScrapeInitiationQueue/twitterAccountListScrapeInitiationJobProcessor.js
- src/server/queues/twitterAccountListScraperQueue/TwitterAccountListScraperJobScheduler.js
- src/server/queues/twitterAccountListScraperQueue/TwitterAccountListScraperQueueFactory.js
- src/server/queues/twitterAccountListScraperQueue/index.js
- src/server/queues/twitterAccountListScraperQueue/twitterAccountListScraperJobProcessor.js
- src/server/utils/__test__/index.test.js
- src/server/utils/__test__/twitter.test.js
- src/server/utils/google.js
- src/server/utils/index.js
- src/server/utils/twitter.js
This PR adds two new queues in order to create the regular synchronization of twitter accounts with a google doc.
The first queue will scrape the document associated with a list, disable twitter accounts associated with that list, and re-enable (or add) any accounts that are on the list according to the scrape.
The second queue is the initiation queue which starts jobs in the first queue for each registered twitter list.
A critical note: this PR adds calculated tech debt.  Specifically, we are storing the google docs as constants.  This is NOT an appropriate use of a constant, but since we are about to change the way twitter lists and newsletters are managed in our system we felt that this was the least onerous approach.
1. `yarn test`
- `yarn migrate`
Resolves #229 
Related to #255
> Add twitter account sync

- src/server/queues/__test__/constants.test.js
- src/server/queues/constants.js
- src/server/queues/twitterAccountListScraperQueue/twitterAccountListScraperJobProcessor.js
This PR fixes a major issue with the twitter account list scraper where it was being triggered every time a twitter *account* was scraped (so, thousands of times a day).
NOTE: this did not impact production, since we were still in QA for this feature (it did not make it past staging yet)
This PR also makes an inconsequential tweak related to accepted column names.
1. `yarn test`
None
Resolves #361
Resolves #362 
Resolves #357
> Hotfix list scraper

- .env.template
- package.json
- src/server/constants.js
- src/server/migrations/20200406190114-add-twitter-account-unique-key.js
- src/server/migrations/20200507181156-create-twitter-account-lists.js
- src/server/migrations/20200531192735-refactor-twitter-account-list-association.js
- src/server/models/TwitterAccount.js
- src/server/models/TwitterAccountList.js
- src/server/queues/twitterAccountListScrapeInitiationQueue/twitterAccountListScrapeInitiationJobProcessor.js
- src/server/queues/twitterAccountListScraperQueue/twitterAccountListScraperJobProcessor.js
- src/server/utils/google.js
- src/server/utils/newsletters.js
This PR adds the database concept of TwitterAccountLists, which replace the previous constant-driven twitter account list architecture.
It updates the twitter account list sync logic to use the database.
It is a draft because it does not yet update the newsletter generation to reflect these changes.
1. Update your environment variables so that the DB urls start with `postgres://` instead of `postgresql://`
2. Wipe out your local DB if I'm being honest
3. re-run migrate
4. Add two rows to `twitter_account_lists`: 
```
0 | national      | 1gLkx2LK3yhS-glpsktWYNqBc9H2zsd7C6TvmgWjL5Kg | 2020-06-11 11:58:45.171008-04 | 2020-06-11 11:58:45.171008-04
1 | northCarolina | 1Z7grw_GQLNMtSVvkUtbXatly_JId7h3yVDX9BWyJetg | 2020-06-11 11:59:13.735023-04 | 2020-06-11 11:59:13.735023-04
```
5. Try running …
> Move Twitter lists to the database

- .travis.yml
This PR adds an encrypted configuration that tells travis to send notifications to our development slack.
None, this is travis
None
Resolves #374
> Add slack to travis notifications
